function generate_Figure1_panels(repoRoot, outDir)
%GENERATE_FIGURE1_PANELS Generate public data-driven panels for Figure 1.
%
% Inputs
%   data/source_data/SourceData_Figure1.xlsx
%
% Outputs
%   results/figure_panels/Figure1/
%     1D_score_angle_curves.svg/.png
%     1E_score_heatmap.svg/.png
%     1F_thetaopt_timeseries.svg/.png
%     1G_relative_fitted_score.svg/.png
%     1H_mouse_summary.svg/.png
%     1C_REQUIRES_RAW_IMAGES.txt
%
% Panels A and B are intentionally not generated. They are conceptual/
% experimental-design artwork assembled manually in Adobe Illustrator and do
% not encode numerical results from the released source-data workbook.
%
% Panel C is intentionally not recreated because the released compact
% numerical package does not contain the representative fluorescence images.
% See the output note and the source-data metadata sheet for the required
% sampled angles/time points.
%
% Public-facing labels use "image score" rather than the legacy term
% "Peak-F". Legacy source-data column names are read without changing values.

if nargin < 1 || isempty(repoRoot)
    repoRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
end
repoRoot = char(repoRoot);
addpath(repoRoot);
repoRoot = setup_repository(repoRoot);

if nargin < 2 || isempty(outDir)
    outDir = fullfile(repoRoot,'results','figure_panels','Figure1');
end
if ~isfolder(outDir), mkdir(outDir); end

xlsx = fullfile(repoRoot,'data','source_data','SourceData_Figure1.xlsx');
if ~isfile(xlsx), error('Source-data workbook not found: %s',xlsx); end

S = ccplot.defaults();

Tfit  = readtable(xlsx,'Sheet','F1_source_panelD_fit_curves','VariableNamingRule','preserve');
Traw  = readtable(xlsx,'Sheet','F1_source_panelD_raw_curves','VariableNamingRule','preserve');
Theat = readtable(xlsx,'Sheet','F1_source_panelE_heatmap','VariableNamingRule','preserve');
Tts   = readtable(xlsx,'Sheet','F1_source_panelsF_G_timeseries','VariableNamingRule','preserve');
Tmouse= readtable(xlsx,'Sheet','F1_source_panelH_depth200','VariableNamingRule','preserve');
Tmeta = readtable(xlsx,'Sheet','F1_source_panelC_image_metadata','VariableNamingRule','preserve');

%% C. Metadata note only
notePath = fullfile(outDir,'1C_REQUIRES_RAW_IMAGES.txt');
fid=fopen(notePath,'w');
if fid<0, error('Could not write: %s',notePath); end
fprintf(fid,['Figure 1C is not generated by the public numerical panel script because the compact repository\n' ...
    'does not contain the representative YFP fluorescence image files.\n\n' ...
    'The released SourceData_Figure1.xlsx sheet F1_source_panelC_image_metadata records the exact\n' ...
    'representative experiment, time points, fixed sampled angle, and time-resolved highest-score sampled angles.\n\n']);
for i=1:height(Tmeta)
    fprintf(fid,'time_index=%d, time_display_min=%.6g, fixed_angle_deg=%.6g, optimized_angle_deg=%.6g\n', ...
        Tmeta.time_index(i),Tmeta.time_display_min(i),Tmeta.fixed_angle_deg(i),Tmeta.optimized_angle_deg(i));
end
fclose(fid);
fprintf('Wrote note: %s\n',notePath);

%% D. Representative normalized score-versus-angle curves
uTimes = unique(Traw.time_index,'stable');
fig=figure('Color','w'); tl=tiledlayout(fig,1,numel(uTimes),'TileSpacing','compact','Padding','compact');
theta0 = Tts.theta_reference_deg(find(isfinite(Tts.theta_reference_deg),1,'first'));
for k=1:numel(uTimes)
    ax=nexttile(tl); hold(ax,'on');
    tr=Traw(Traw.time_index==uTimes(k),:);
    tf=Tfit(Tfit.time_index==uTimes(k),:);
    ylims=[0.70 1.03];
    if ~isempty(tf)
        ccplot.shade_xrange(ax,tf.low95_deg(1),tf.high95_deg(1),ylims,[0.45 0.45 0.45],0.88);
        plot(ax,tf.angle_deg,tf.peakf_norm_fit,'k-','LineWidth',S.lineWidth);
        [~,ii]=min(abs(tf.angle_deg-tf.thetaopt_deg(1)));
        plot(ax,tf.thetaopt_deg(1),tf.peakf_norm_fit(ii),'o','MarkerFaceColor','k','MarkerEdgeColor','k','MarkerSize',4.5);
    end
    scatter(ax,tr.angle_deg,tr.peakf_norm_raw,18,'o','MarkerFaceColor','w','MarkerEdgeColor','k','LineWidth',0.8);
    xline(ax,theta0,'--','Color',S.gray,'LineWidth',0.9);
    xlim(ax,[min(tr.angle_deg) max(tr.angle_deg)]); ylim(ax,ylims);
    title(ax,sprintf('%.1f min',tr.time_display_min(1)),'FontName',S.fontName,'FontSize',S.titleFontSize,'FontWeight','normal');
    xlabel(ax,'Correction-collar angle (°)','Interpreter','none');
    if k==1, ylabel(ax,'Normalized image score','Interpreter','none'); else, ax.YTickLabel=[]; end
    ccplot.style_axes(ax);
end
ccplot.export_panel(fig,fullfile(outDir,'1D_score_angle_curves.svg'),[24 6.8]); close(fig);

%% E. Heatmap across time and sampled angle
uT=unique(Theat.time_index,'stable'); uA=unique(Theat.angle_deg,'stable');
Z=nan(numel(uA),numel(uT)); tDisplay=nan(1,numel(uT));
for it=1:numel(uT)
    tt=Theat(Theat.time_index==uT(it),:); tDisplay(it)=tt.time_display_min(1);
    for ia=1:numel(uA)
        idx=tt.angle_deg==uA(ia); if any(idx), Z(ia,it)=tt.peakf_norm(find(idx,1)); end
    end
end
fig=figure('Color','w'); ax=axes(fig); hold(ax,'on');
imagesc(ax,tDisplay,uA,Z); set(ax,'YDir','normal');
colormap(ax,parula(256)); caxis(ax,[0.70 1.00]); cb=colorbar(ax); cb.Label.String='Normalized image score'; cb.FontName=S.fontName; cb.FontSize=S.fontSize;
plot(ax,Tts.time_display_min,Tts.thetaopt_fit_deg,'w-','LineWidth',1.4);
yline(ax,theta0,'w--','LineWidth',1.0);
xlabel(ax,'Time (min)'); ylabel(ax,'Correction-collar angle (°)','Interpreter','none');
ccplot.style_axes(ax);
ccplot.export_panel(fig,fullfile(outDir,'1E_score_heatmap.svg'),[10 8]); close(fig);

%% F. θopt(t) and W95 band
fig=figure('Color','w'); ax=axes(fig); hold(ax,'on');
ccplot.shade_band(ax,Tts.time_display_min,Tts.low95_deg,Tts.high95_deg,[0.45 0.45 0.45],0.82);
plot(ax,Tts.time_display_min,Tts.thetaopt_fit_deg,'k-','LineWidth',1.4);
yline(ax,theta0,'--','Color',S.gray,'LineWidth',1.0);
xlabel(ax,'Time (min)'); ylabel(ax,'Estimated optimal angle, θopt (°)','Interpreter','none');
ccplot.style_axes(ax);
ccplot.export_panel(fig,fullfile(outDir,'1F_thetaopt_timeseries.svg'),[10 7]); close(fig);

%% G. Relative fitted score at the initial angle
fig=figure('Color','w'); ax=axes(fig); hold(ax,'on');
plot(ax,Tts.time_display_min,Tts.retention,'k-','LineWidth',1.3);
yline(ax,0.95,'--','Color',S.gray,'LineWidth',1.0);
ylim(ax,[0.94 1.005]);
xlabel(ax,'Time (min)'); ylabel(ax,'Relative fitted score','Interpreter','none');
ccplot.style_axes(ax);
ccplot.export_panel(fig,fullfile(outDir,'1G_relative_fitted_score.svg'),[10 7]); close(fig);

%% H. Mouse-level summary
metrics = {'theta_range_deg','mean_width95_deg','min_retention_fit_initial'};
ylabels = {'Temporal range of θopt (°)','Mean W95 (°)','Minimum relative fitted score'};
fig=figure('Color','w'); tl=tiledlayout(fig,1,3,'TileSpacing','compact','Padding','compact');
for k=1:3
    ax=nexttile(tl); hold(ax,'on');
    vals=Tmouse.(metrics{k});
    ccplot.iqr_box(ax,1,vals,'Color',[0 0 0],'BoxWidth',0.50,'PointSize',24,'JitterWidth',0.18,'FaceBlend',0.88);
    xlim(ax,[0.55 1.45]); set(ax,'XTick',[]);
    ylabel(ax,ylabels{k},'Interpreter','none');
    if k==3, ylim(ax,[0.94 1.005]); yline(ax,0.95,'--','Color',S.gray); end
    ccplot.style_axes(ax);
end
ccplot.export_panel(fig,fullfile(outDir,'1H_mouse_summary.svg'),[16 7]); close(fig);

fprintf('\nFigure 1 data-panel generation completed.\n');
fprintf('Panels A and B are conceptual artwork and are intentionally not generated.\n');
fprintf('Panel C requires representative raw fluorescence images.\n');
fprintf('Output: %s\n',outDir);
end
